

name: Zip Files

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Default value if no value is explicitly provided
        default: 'RunZipBuilding'
        # Input has to be provided for the workflow to run
        required: true


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: CoffeShop
          dest: result.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
